engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "client/**/*.js"
  - "server/**/*.js"
exclude_paths:
  - "node_modules/"
  - "template/*"
  - "client/"
  - "server/test"

