engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "client/src/**/*.js"
  - "client/src/**/*.jsx"
  - "server/**/*.js"
exclude_paths:
  - "node_modules/"
  - "template/*"
  - "client/__test__/**/*.js"
  - "server/server-test"
  - "server/public/*"
  - "server/migrations/"
  - "server/models/"
  - "**/test/*.js"
  - "**/*.test.js"
  - "client/src/actions/"

